version: '3.5'
services:
sample-app:
    container_name: mytest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=${NODE_ENV}